pipeline {
    agent any 

    tools {
        maven 'maven-3.9.2'
    }

    stages {
        stage ('Build-Maven') {
            steps {
                sh '''
                    cd ./maven/simple-war/
                    mvn clean package
                    cd ./target/
                    ls
                '''
            }
        }

        stage ('Deploy-Tomcat') {
            steps {
                script {
                    deploy adapters: [tomcat9(credentialsId: '29ff008e-47af-43cc-a67d-e4b3e447ee39', path: '', url: 'http://13.235.27.142:8080/')], contextPath: '/itdefined-war-1.0.0', war: 'maven/simple-war/target/itdefined-war-1.0.0.war'
                }
            }
        }
    }

}
